import 'package:e_cart1/model/Product.dart';

class MyProducts {
  static List<Product> allProducts = [
    //---shoesss------
    Product(
      id: 1,
      name: 'Nike air',
      description: 'clean versatile shoe for men',
      price: 880,
      image: 'assets/sneakers_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red Tape',
      description: 'Red Tape for men',
      price: 600,
      image: 'assets/sneakers_pics/2.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike mark111',
      description: 'Clean nike mark 111 shoes extra comfort',
      price: 1000,
      image: 'assets/sneakers_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas',
      description: 'Black adidas original with smoothness',
      price: 1100,
      image: 'assets/sneakers_pics/4.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas running shoes',
      description: 'Shoes for fast run and comfort',
      price: 2000,
      image: 'assets/sneakers_pics/5.png',
      category: 'Available',
      quantity: 1,
    ),

    // jacks--------------------
    Product(
      id: 1,
      name: 'Nike jackets 200',
      description: 'blacket comfort jackets in winters',
      price: 1800,
      image: 'assets/jacket_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Perfomax jackets',
      description: 'blacket comfort jackets in winters',
      price: 1500,
      image: 'assets/jacket_pics/2.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike dual color',
      description: 'blacket comfort jackets in winters',
      price: 2200,
      image: 'assets/jacket_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red tape jackets',
      description: 'blacket comfort jackets in winters',
      price: 3000,
      image: 'assets/jacket_pics/4.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jordan',
      description: 'blacket comfort jackets in winters',
      price: 3300,
      image: 'assets/jacket_pics/5.png',
      category: 'Out of stock',
      quantity: 1,
    ),
  ];

  static List<Product> Jackets = [
    Product(
      id: 1,
      name: 'Nike jackets 200',
      description: 'blacket comfort jackets in winters',
      price: 1800,
      image: 'assets/jacket_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Perfomax jackets',
      description: 'blacket comfort jackets in winters',
      price: 1500,
      image: 'assets/jacket_pics/2.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike dual color',
      description: 'blacket comfort jackets in winters',
      price: 2200,
      image: 'assets/jacket_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red tape jackets',
      description: 'blacket comfort jackets in winters',
      price: 3000,
      image: 'assets/jacket_pics/4.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jordan',
      description: 'blacket comfort jackets in winters',
      price: 3300,
      image: 'assets/jacket_pics/5.png',
      category: 'Out of stock',
      quantity: 1,
    ),
  ];

  static List<Product> shoes = [
    Product(
      id: 1,
      name: 'Nike air',
      description: 'clean versatile shoe for men',
      price: 880,
      image: 'assets/sneakers_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red Tape',
      description: 'Red Tape for men',
      price: 600,
      image: 'assets/sneakers_pics/2.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike mark111',
      description: 'Clean nike mark 111 shoes extra comfort',
      price: 1000,
      image: 'assets/sneakers_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas',
      description: 'Black adidas original with smoothness',
      price: 1100,
      image: 'assets/sneakers_pics/4.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas running shoes',
      description: 'Shoes for fast run and comfort',
      price: 2000,
      image: 'assets/sneakers_pics/5.png',
      category: 'Available',
      quantity: 1,
    ),
  ];
}
