import 'package:e_cart1/model/Product.dart';

class MyProducts {
  static List<Product> allProducts = [
    //---shoesss------
    Product(
      id: 1,
      name: 'Nike air',
      description: ' Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph. A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long. Ultimately, a paragraph is a sentence or group of sentences that sup Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 880,
      image: 'assets/sneakers_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red Tape Elevate your ',
      description: 'Red Tape for men running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 600,
      image: 'assets/sneakers_pics/2.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike mark111',
      description: 'Clean nike mark 111 shoes extra comfort Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1000,
      image: 'assets/sneakers_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas',
      description: 'Black adidas original with smoothness Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1100,
      image: 'assets/sneakers_pics/4.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas running shoes',
      description: 'Shoes for fast run and comfort Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 2000,
      image: 'assets/sneakers_pics/5.png',
      category: 'Available',
      quantity: 1,
    ),

    // jacks--------------------
    Product(
      id: 1,
      name: 'Nike jackets 200',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1800,
      image: 'assets/jacket_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Perfomax jackets',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1500,
      image: 'assets/jacket_pics/2.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike dual color',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 2200,
      image: 'assets/jacket_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red tape jackets',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 3000,
      image: 'assets/jacket_pics/4.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jordan',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 3300,
      image: 'assets/jacket_pics/5.png',
      category: 'Out of stock',
      quantity: 1,
    ),
  ];

  static List<Product> Jackets = [
    Product(
      id: 1,
      name: 'Nike jackets 200',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1800,
      image: 'assets/jacket_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Perfomax jackets',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1500,
      image: 'assets/jacket_pics/2.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike dual color',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 2200,
      image: 'assets/jacket_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red tape jackets',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 3000,
      image: 'assets/jacket_pics/4.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jordan',
      description: 'blacket comfort jackets in winters Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 3300,
      image: 'assets/jacket_pics/5.png',
      category: 'Out of stock',
      quantity: 1,
    ),
  ];

  static List<Product> shoes = [
    Product(
      id: 1,
      name: 'Nike air',
      description: 'clean versatile shoe for men Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 880,
      image: 'assets/sneakers_pics/1.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Red Tape',
      description: 'Red Tape for men Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 600,
      image: 'assets/sneakers_pics/2.png',
      category: 'Out of stock',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike mark111',
      description: 'Clean nike mark 111 shoes extra comfort Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1000,
      image: 'assets/sneakers_pics/3.png',
      category: 'Trending',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas',
      description: 'Black adidas original with smoothness Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 1100,
      image: 'assets/sneakers_pics/4.png',
      category: 'Trending now',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'adidas running shoes',
      description: 'Shoes for fast run and comfort Elevate your running experience with our ComfortStride Running Shoes. Designed for optimum performance and comfort, these shoes are a perfect blend of style and functionality.',
      price: 2000,
      image: 'assets/sneakers_pics/5.png',
      category: 'Available',
      quantity: 1,
    ),
  ];
}
